version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
         - pgdata:/var/lib/postgresql/data
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"
volumes: 
    pgdata: